<Project Sdk="Nice3point.Revit.Sdk/6.1.2">

	<PropertyGroup>
		<UseWPF>true</UseWPF>
		<DeployAddin>true</DeployAddin>
		<LaunchRevit>true</LaunchRevit>
		<IsRepackable>false</IsRepackable>
		<EnableDynamicLoading>true</EnableDynamicLoading>
		<Configurations>Debug.R24;Debug.R25;Debug.R26</Configurations>
		<Configurations>$(Configurations);Release.R24;Release.R25;Release.R26</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="$(Configuration.Contains('R24'))">
		<RevitVersion>2024</RevitVersion>
		<TargetFramework>net48</TargetFramework>
	</PropertyGroup>
	<PropertyGroup Condition="$(Configuration.Contains('R25'))">
		<RevitVersion>2025</RevitVersion>
		<TargetFramework>net8.0-windows</TargetFramework>
	</PropertyGroup>
	<PropertyGroup Condition="$(Configuration.Contains('R26'))">
		<RevitVersion>2026</RevitVersion>
		<TargetFramework>net8.0-windows</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<!-- Revit Platform -->
		<PackageReference Include="Nice3point.Revit.Toolkit" Version="$(RevitVersion).*" />
		<PackageReference Include="Nice3point.Revit.Extensions" Version="$(RevitVersion).*" />
		<PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="$(RevitVersion).*" />
		<PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="$(RevitVersion).*" />
		<PackageReference Include="Nuke.Common" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Commands\Drawing\Clone\" />
		<Folder Include="Commands\Drawing\RebarSchedule\Models\" />
		<Folder Include="Commands\Drawing\RebarSchedule\ViewModels\" />
		<Folder Include="Commands\Rebar\" />
		<Folder Include="Utils\Geometry\" />
	</ItemGroup>

	<!-- Copy Family files (.rfa) to output directory -->

	<!-- Copy Parameter files (.txt) to output directory -->
	<ItemGroup>
		<None Include="ShareParameter\*.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>Parameter\%(Filename)%(Extension)</Link>
		</None>
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="Services\**" />
		<EmbeddedResource Remove="Services\**" />
		<None Remove="Services\**" />
		<Page Remove="Services\**" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="Resources\Icons\icons8-room-16.png" />
		<None Remove="Resources\Icons\icons8-room-32.png" />
		<None Remove="Resources\Icons\room16.png" />
		<None Remove="Resources\Icons\room32.png" />
		<None Remove="ShareParameter\WH_Rebar_Description.txt" />
	</ItemGroup>
	<ItemGroup>
		<Resource Include="Resources\Icons\room16.png" />
		<Resource Include="Resources\Icons\room32.png" />
		<EmbeddedResource Include="ShareParameter\WH_Rebar_Description.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>

</Project>