<Project Sdk="Microsoft.NET.Sdk">
	
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <Version>1.0</Version>
    <Title>GH_Tekla_Dwg</Title>
    <Description>Description of GH_Tekla_Dwg</Description>
    <TargetExt>.gha</TargetExt>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="7.13.21348.13001" IncludeAssets="compile;build" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="Tekla.Macros">
      <HintPath>..\..\..\Khoa hoc API Tekla\Tekla.Macros.dll</HintPath>
    </Reference>
    <Reference Include="Tekla.Macros.Akit">
      <HintPath>..\..\..\Khoa hoc API Tekla\Tekla.Macros.Akit.dll</HintPath>
    </Reference>
    <Reference Include="Tekla.Macros.Runtime">
      <HintPath>..\..\..\Khoa hoc API Tekla\Tekla.Macros.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Tekla.Macros.Wpf">
      <HintPath>..\..\..\Khoa hoc API Tekla\Tekla.Macros.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="Tekla.Macros.Wpf.Runtime">
      <HintPath>..\..\..\Khoa hoc API Tekla\Tekla.Macros.Wpf.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Tekla.Structures">
      <HintPath>..\..\..\Khoa hoc API Tekla\Tekla.Structures.dll</HintPath>
    </Reference>
    <Reference Include="Tekla.Structures.Drawing">
      <HintPath>..\..\..\Khoa hoc API Tekla\Tekla.Structures.Drawing.dll</HintPath>
    </Reference>
    <Reference Include="Tekla.Structures.Model">
      <HintPath>..\..\..\Khoa hoc API Tekla\Tekla.Structures.Model.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Resources\add rebar dim.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\arrange rebar mark.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\CU dwg.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\cut parts.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Dim.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\dwg rebar.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Edge Points.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\get 2nd parts.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\get view.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\hide rebar.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\LH.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\rebar dim.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\rebar name.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\rebar prefix.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\rotate view.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\section view.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\view height.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\view property.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\view width.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup Condition="$(Configuration) == 'Debug' AND $([MSBuild]::IsOSPlatform(Windows))">
    <StartProgram>C:\Program Files\Rhino 7\System\Rhino.exe</StartProgram>
      <StartArguments>/runscript="_-RunScript (
        Set GH = Rhino.GetPlugInObject(""Grasshopper"") 
        Call GH.OpenDocument(""C:\Users\hoang_anhdung\Desktop\TEST_GH_TEKLA_API.gh"")
      )"</StartArguments>
    <StartAction>Program</StartAction>
  </PropertyGroup>
	
</Project>
